apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
data:
  # Database Hosts
  USER_DB_HOST: "user-db"
  USER_DB_PORT: "5432"
  USER_DB_NAME: "users_db"

  PRODUCT_DB_HOST: "product-db"
  PRODUCT_DB_PORT: "5432"
  PRODUCT_DB_NAME: "products_db"

  CART_DB_HOST: "cart-db"
  CART_DB_PORT: "5432"
  CART_DB_NAME: "carts_db"

  ORDER_DB_HOST: "order-db"
  ORDER_DB_PORT: "5432"
  ORDER_DB_NAME: "orders_db"

  PAYMENT_DB_HOST: "payment-db"
  PAYMENT_DB_PORT: "5432"
  PAYMENT_DB_NAME: "payments_db"

  NOTIFICATION_DB_HOST: "notification-db"
  NOTIFICATION_DB_PORT: "5432"
  NOTIFICATION_DB_NAME: "notifications_db"

  # Eureka
  EUREKA_URL: "http://eureka:8761/eureka/"

  # Kafka
  KAFKA_BROKER_ID: "1"
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"

  # Spring Profile
  SPRING_PROFILES_ACTIVE: "docker"

  # Elasticsearch
  ES_JAVA_OPTS: "-Xms512m -Xmx512m"

  # Logstash
  LS_JAVA_OPTS: "-Xmx256m -Xms256m"

